
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 9;
  public static final int POWER = 33;
  public static final int MULT = 31;
  public static final int CHAR = 55;
  public static final int TCHAR = 3;
  public static final int LESSTHN = 37;
  public static final int POOL = 18;
  public static final int TFLOAT = 7;
  public static final int INT = 56;
  public static final int LSQR = 48;
  public static final int LCURL = 47;
  public static final int NOT = 25;
  public static final int AND = 26;
  public static final int RPAR = 45;
  public static final int EVAL = 52;
  public static final int IN = 34;
  public static final int OR = 27;
  public static final int TDEF = 10;
  public static final int BOOL = 59;
  public static final int COMMA = 53;
  public static final int SEMICOL = 51;
  public static final int TBOOL = 4;
  public static final int FI = 16;
  public static final int DIV = 32;
  public static final int RAT = 58;
  public static final int MOREEQ = 40;
  public static final int LOOP = 17;
  public static final int ASSIGN = 43;
  public static final int LESSEQ = 38;
  public static final int MAIN = 2;
  public static final int IF = 13;
  public static final int DOT = 50;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int error = 1;
  public static final int ADD = 29;
  public static final int DCOL = 36;
  public static final int IDENT = 54;
  public static final int BREAK = 19;
  public static final int FDEF = 12;
  public static final int EQ = 41;
  public static final int IMPLY = 28;
  public static final int TOP = 24;
  public static final int RCURL = 46;
  public static final int COL = 35;
  public static final int TINT = 5;
  public static final int DICT = 8;
  public static final int ELSE = 15;
  public static final int READ = 21;
  public static final int RSQR = 49;
  public static final int MORETHN = 39;
  public static final int FLOAT = 57;
  public static final int THEN = 14;
  public static final int STRING = 60;
  public static final int LPAR = 44;
  public static final int LEN = 23;
  public static final int ALIAS = 11;
  public static final int TRAT = 6;
  public static final int SUB = 30;
  public static final int PRINT = 22;
  public static final int NOTEQ = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "TCHAR",
  "TBOOL",
  "TINT",
  "TRAT",
  "TFLOAT",
  "DICT",
  "SEQ",
  "TDEF",
  "ALIAS",
  "FDEF",
  "IF",
  "THEN",
  "ELSE",
  "FI",
  "LOOP",
  "POOL",
  "BREAK",
  "RETURN",
  "READ",
  "PRINT",
  "LEN",
  "TOP",
  "NOT",
  "AND",
  "OR",
  "IMPLY",
  "ADD",
  "SUB",
  "MULT",
  "DIV",
  "POWER",
  "IN",
  "COL",
  "DCOL",
  "LESSTHN",
  "LESSEQ",
  "MORETHN",
  "MOREEQ",
  "EQ",
  "NOTEQ",
  "ASSIGN",
  "LPAR",
  "RPAR",
  "RCURL",
  "LCURL",
  "LSQR",
  "RSQR",
  "DOT",
  "SEMICOL",
  "EVAL",
  "COMMA",
  "IDENT",
  "CHAR",
  "INT",
  "FLOAT",
  "RAT",
  "BOOL",
  "STRING"
  };
}

